### ISSUE TITLE
Check that all endpoints have at least some testing

### ISSUE THREAD

**Issue by lmullen** [chnm/apiary#16]
But no point doing this until the API stabilizes.

**Comment by lmullen** [comment]
Can we also improve the way that testing is done?

**Comment by lmullen** [comment]
@hepplerj I think this is actually done, right? If so, we can close it out.

**Comment by lmullen** [comment]
Feel free to reopen if it is not done.

**Comment by hepplerj** [comment]
Yep, we are up to date on this. Thanks.
